### ISSUE TITLE
Decrypt fails when ValueRange is less than input

### ISSUE THREAD

**Issue by acidreign** [loostro/cryptomute#13]
I'm trying to encrypt ids that are in the hundreds of millions (9 digits)  into an 8 digit integer. The encrypt function works fine. The decrypt function does not decrypt to the correct input. If I increase the ValueRange from 8 to 9 digits decrypt works.

I'm not well versed in the algorithm used so it could be that this just an inherent limitation that I'm not aware of.

Example of the issue:
```php
$cryptomute = new Cryptomute(
    'aes-128-cbc',      // cipher
    '0123456789zxcvbn', // base key
    7                   // number of rounds
);

// doesn't work
$cryptomute->setValueRange(0, 99999999);
// does work
//$cryptomute->setValueRange(0, 999999999);

$password = '0123456789qwerty';
$iv = '0123456789abcdef';

for ($i = 100000000; $i <= 100000010; $i++) {
    $encoded = $cryptomute->encrypt($i, 10, true, $password, $iv);
    $decoded = $cryptomute->decrypt($encoded, 10, true, $password, $iv);
    echo "ID: ".$i." DECODED: ".$decoded." ENCODED: ".$encoded."<br>";
}
```

**Comment by loostro** [comment]
@acidreign This is expected behaviour. Format preserving encryption means you're performing a transformation that maps one element from given domain into another element from the same domain.

The `setValueRange` function is used to set the domain, eg. for 3-digit numbers you would do `setValueRange(0,999)`.

You cannot apply a FPE transformation to a value out of domain range and expect to be able to decrypt it.

I will add a check and throw an expection if input is out of domain.

**Comment by acidreign** [comment]
@loostro Ok, that makes sense. Thanks for the update!
